# Basic
title: è¢å‡¤é¸£
subtitle: æ¬¢è¿æ¥åˆ°æˆ‘çš„ä¸ªäººç«™~
description: æœ€å¥½çš„å­¦ä¹ æ—¶é—´æ˜¯åå¹´å‰ï¼Œå…¶æ¬¡æ˜¯ç°åœ¨ï¼
# å¤´åƒé‡Œé¢çš„æ ‡é¢˜
avatarTitle: Mingo
# å¤´åƒé‡Œé¢çš„æè¿°
avatarDesc: iOS / ä¸ªäººç¬”è®°
url: "http://baixin.io"

# Comment
comment:
    # disqus: leopard
    duoshuo: yfmingo#leopard 

# Social
social:
    weibo: 3414294504 
    github: yfming93
    # twitter: 
    mail: yfmingo@163.com

# ç™¾åº¦ç»Ÿè®¡ 
# ä½¿ç”¨åšå®¢æ¨¡æ¿è¯·å»æ‰æˆ–è€…æ›´æ¢ id 
baidu:
    id: 9241bf337f3366ee1aea666f56466cf1
       #8ba1c6be0953b6f9c2ba38e57f615421   åŸæ¥æ¨¡æ¿

# Google Analytics
# ä½¿ç”¨åšå®¢æ¨¡æ¿è¯·å»æ‰æˆ–è€…æ›´æ¢ id
ga:
    id: UA-89635745-1
       #UA-84134159-3 åŸæ¥æ¨¡æ¿

    host: auto  


# ã€Š----------------- ä¸Šé¢çš„ä¿¡æ¯ä¿®æ”¹æˆä½ è‡ªå·±çš„ ---------------------------ã€‹
#
#
#  _post/ ä¸‹çš„æ–‡ç« æ›´æ¢æˆä½ è‡ªå·±çš„æ–‡ç« 
#  å¸®å¿™starä¸€ä¸‹ï¼Œæ„Ÿè°¢~ğŸ˜† åœ°å€ï¼š https://github.com/leopardpan/leopardpan.github.io
#
#
# ã€Š--------------- ä¸‹é¢çš„ä¿¡æ¯å¯ä»¥è‡ªè¡Œé€‰æ‹©æ˜¯å¦ä¿®æ”¹ ------------------------ã€‹


permalink: /:year/:month/:title/
# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: clear

# The blog button should not be removed.
blog_button:
    title: åšå®¢ä¸»é¡µ

# Navigation buttons in the front page.s
nav:
    - {title: æ‰€æœ‰æ–‡ç« , description: archive, url: '/archive'}
    - {title: æ ‡ç­¾, description: tags, url: '/tags'}
    - {title: å…³äºæˆ‘, description: about, url: '/about'}

# Pagination
gems: [jekyll-paginate] #[jekyll-paginate,jekyll-sitemap]
paginate: 20
paginate_path: "page/:num/"


